### ISSUE TITLE
Is "into" allowed in a processes' input section?

### ISSUE THREAD

**Issue by nh13** [nextflow-io/nextflow#1625]
This silently works on 20.4.1:

```
process Foo {
  input:
  path "data.txt" into someChannel
}
```

But what does it mean to have "into" in the "input" section?  Shouldn't this be an error (ex. "cannot use 'into' in the input section").  What am I missing?  Thank-you for your help in advance.

**Comment by pditommaso** [comment]
I get the following error

```
Script compilation error
- file : /Users/pditommaso/Projects/nextflow/t.nf
- cause: Invalid process definition -- Make sure the process ends with a script wrapped by quote characters @ line 1, column 1.
   process Foo {
   ^

1 error
```

**Comment by nh13** [comment]
Does it still generate that error if the process is never executed?

**Comment by nh13** [comment]
It was not executed as the one if the input channels was empty.

**Comment by pditommaso** [comment]
I'm still getting  "compile" time error even with an empty channel.

**Comment by pditommaso** [comment]
This thread looks stalled. Feel free to comment/re-open if needed.
